version: 2
jobs:
  build:
    working_directory: ~/izzy-json-api-android
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Build
          command: ./gradlew clean assemble
  static_analysis:
    working_directory: ~/izzy-json-api-android
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Static analysis
          command: ./gradlew ktlintCheck detekt
  tests:
    working_directory: ~/izzy-json-api-android
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Tests
          command: ./gradlew test
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_test_results:
          path: build/test-results
workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - static_analysis
      - tests
