version: 2
jobs:
  build:
    working_directory: ~/izzy-json-api-android
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Build
          command: ./gradlew clean assemble
      - run:
          name: Static analysis
          command: ./gradlew ktlint detekt
      - run:
          name: Tests
          command: ./gradlew test
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_test_results:
          path: build/test-results