version: 2
jobs:
  build:
    working_directory: ~/izzy-json-api-android
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Build
          command: ./gradlew clean assemble
  static_analysis:
    working_directory: ~/izzy-json-api-android
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Static analysis
          command: ./gradlew ktlint detekt
  tests:
    working_directory: ~/izzy-json-api-android
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Tests
          command: ./gradlew test
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_test_results:
          path: build/test-results
  deploy:
    working_directory: ~/izzy-json-api-android
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Publish to Bintray
          command: ./gradlew clean build bintrayUpload -PdryRun=false
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - static_analysis
      - tests
      - hold:
          type: approval
          requires:
            - build
            - static_analysis
            - tests
          filters:
            branches:
              only:
                - master
                - develop
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only:
                - master
                - develop
